choco install 7zip -y
choco install 7zip.install -y
choco install autoit -y
choco install autoit.install -y
choco install bat -y
choco install crystaldiskmark -y
choco install dbgate -y
choco install fiddler -y
choco install filezilla -y
choco install filezilla.server -y
choco install Firefox -y
choco install fontforge -y
choco install fzf -y
choco install gifcam -y
# choco install github-desktop -y
choco install greenshot -y
choco install InkScape -y
choco install irfanview -y
choco install lunacy -y
# choco install manictime -y
# choco install manictime.install -y
choco install mysql.workbench -y
choco install netfx-4.6.2 -y
choco install obs-studio -y
choco install obs-studio.install -y
choco install pandoc -y
choco install path-copy-copy -y
choco install pdfsam -y
choco install pdfsam.install -y
choco install pencil -y
choco install postman -y
choco install potplayer -y
choco install powertoys -y
choco install sharpkeys -y
choco install slack -y
choco install StarUML -y
choco install strokesplus -y
choco install strokesplus.install -y
choco install teamviewer -y
choco install thunderbird -y
choco install totalcommander -y
choco install treesizefree -y
choco install typora -y
choco install velocity -y
choco install virustotaluploader -y
choco install vlc -y
choco install winmerge -y
choco install zeal -y
choco install zeal.install -y
choco install zoomit -y