code --install-extension 4ern.4ern
code --install-extension AbhijoyBasak.nestjs-files
code --install-extension adam-watters.vscode-color-pick
code --install-extension adpyke.codesnap
code --install-extension adrianwilczynski.csharp-to-typescript
code --install-extension adrianwilczynski.namespace
code --install-extension adrianwilczynski.switcher
code --install-extension agauniyal.vscode-caniuse
code --install-extension AiryShift.spaces-inside-braces
code --install-extension akamud.vscode-caniuse
code --install-extension akfish.vscode-devdocs
code --install-extension akhaled.key-bindings-to-md
code --install-extension alanmbarr.quotify
code --install-extension alefragnani.Bookmarks
code --install-extension alexkrechik.vsvarsinserter
code --install-extension andersonmfjr.vue-jumptotag
code --install-extension andi1984.tinypng
code --install-extension angelgonzalez.loremzombie
code --install-extension Angular.ng-template
code --install-extension anseki.vscode-color
code --install-extension anweber.statusbar-commands
code --install-extension artlaman.chalice-icon-theme
code --install-extension arturock.gitstash
code --install-extension Asuka.insertnumbers
code --install-extension atarabi.ae-script-runner
code --install-extension auchenberg.vscode-browser-preview
code --install-extension avocode.avocode
code --install-extension ban.spellright
code --install-extension bbenoist.QML
code --install-extension bhughes339.replacerules
code --install-extension bierner.color-info
code --install-extension bierner.markdown-checkbox
code --install-extension bierner.markdown-preview-github-styles
code --install-extension blackmery.vscode-switcher
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bradgashler.htmltagwrap
code --install-extension brpaz.devhints
code --install-extension capaj.vscode-exports-autocomplete
code --install-extension cdes.wrap-with-template-string
code --install-extension cdonohue.quill-icons
code --install-extension ChakrounAnas.turbo-console-log
code --install-extension chriskirknielsen.visubezier
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension ChristianAlexander.flip
code --install-extension christopherstyles.html-entities
code --install-extension chrisvltn.log-wrapper-for-vscode
code --install-extension chrisvltn.vs-code-semicolon-insertion
code --install-extension chrmarti.regex
code --install-extension cmstead.js-codeformer
code --install-extension cmstead.jsrefactor
code --install-extension codemooseus.vscode-devtools-for-chrome
code --install-extension codespaces-contrib.codeswing
code --install-extension codezombiech.gitignore
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension craigthomas.supersharp
code --install-extension cschleiden.vscode-github-actions
code --install-extension csholmq.excel-to-markdown-table
code --install-extension cssho.vscode-svgviewer
code --install-extension cweijan.vscode-database-client2
code --install-extension dakara.transformer
code --install-extension dariofuzinato.vue-peek
code --install-extension darkriszty.markdown-table-prettify
code --install-extension dbankier.vscode-quick-select
code --install-extension DeepKolos.change-color
code --install-extension DeepScan.vscode-deepscan
code --install-extension deerawan.vscode-dash
code --install-extension DengSir.template-generator-vscode
code --install-extension dineug.vuerd-vscode
code --install-extension dinhani.divider
code --install-extension domodev.workspace-gitignore
code --install-extension DonutLaser.module-exports
code --install-extension DosSantosGabriel.linux-cheatsheet
code --install-extension drekevist.multiline-move
code --install-extension DSKWRK.vscode-generate-getter-setter
code --install-extension dzhavat.css-flexbox-cheatsheet
code --install-extension dzhavat.css-initial-value
code --install-extension dzhavat.git-cheatsheet
code --install-extension eamodio.gitlens
code --install-extension electrotype.windows-explorer-context-menu
code --install-extension enochc.copy-relative-path
code --install-extension Equinusocio.moxer-icons
code --install-extension eridem.vscode-postman
code --install-extension fabiospampinato.vscode-highlight
code --install-extension febean.vue-format
code --install-extension fireside21.cshtml
code --install-extension firsttris.vscode-jest-runner
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension formulahendry.docker-explorer
code --install-extension formulahendry.dotnet-test-explorer
code --install-extension Fraser.live-coder
code --install-extension frasercrosbie.csharp-model-to-builder
code --install-extension frhtylcn.pythonsnippets
code --install-extension Fudge.auto-using
code --install-extension FullStackFlamingo.vscode-vue-component-importer
code --install-extension funkyremi.vscode-google-translate
code --install-extension fweber.vue-create-component
code --install-extension gebilaoxiong.vscode-flatland-icon-theme
code --install-extension geddski.macros
code --install-extension gencer.html-slim-scss-css-class-completion
code --install-extension gimenete.github-linker
code --install-extension GitHub.vscode-pull-request-github
code --install-extension giyyapan.commander
code --install-extension giyyapan.fast-snippet
code --install-extension GrapeCity.gc-excelviewer
code --install-extension Gruntfuggly.on-idle
code --install-extension Gruntfuggly.todo-tree
code --install-extension guosong.bracketselection
code --install-extension hbenl.vscode-test-explorer
code --install-extension hdg.live-html-previewer
code --install-extension hediet.debug-visualizer
code --install-extension hediet.vscode-drawio
code --install-extension helixquar.randomeverything
code --install-extension henoc.svgeditor
code --install-extension hideoo.toggler
code --install-extension Ho-Wan.vscode-trello-viewer
code --install-extension hollowtree.vue-snippets
code --install-extension HookyQR.beautify
code --install-extension HookyQR.minify
code --install-extension humao.rest-client
code --install-extension HungVo.htext
code --install-extension IBM.output-colorizer
code --install-extension ilich8086.launcher
code --install-extension immament.vscode-ngrx-uml
code --install-extension inu1255.easy-snippet
code --install-extension ionutvmi.path-autocomplete
code --install-extension ipatalas.vscode-totalcommander
code --install-extension ishiyama.vue-autoimport
code --install-extension jakob101.RelativePath
code --install-extension jakubszalaty.go-to-word
code --install-extension jaydenlin.google-complete-me
code --install-extension jccr.sandbox
code --install-extension jchannon.csharpextensions
code --install-extension jeff-hykin.macro-commander
code --install-extension jingkaizhao.vscode-redux-devtools
code --install-extension jmfirth.vsc-space-block-jumper
code --install-extension jmrog.vscode-nuget-package-manager
code --install-extension john-lee.copy-relative-path
code --install-extension johnguo.columnpaste
code --install-extension johnpyp.vscode-jumpy-plus
code --install-extension johnrazeur.hyper-shortcut
code --install-extension jomeinaster.bracket-peek
code --install-extension jtlowe.vscode-icon-theme
code --install-extension JulioGold.vscode-smart-split-into-lines
code --install-extension junv.recent-files
code --install-extension jzarzoso.break-from-comma
code --install-extension kaishuu0123.vscode-erd-preview
code --install-extension kaiwood.center-editor-window
code --install-extension kaiwood.indentation-level-movement
code --install-extension kavod-io.vscode-jest-test-adapter
code --install-extension KevinRose.vsc-python-indent
code --install-extension kontrail.vscode-svg-dev
code --install-extension krisanalfa.tinkerHere
code --install-extension kvxymatt.class-extractor
code --install-extension lacroixdavid1.vscode-format-context-menu
code --install-extension lannonbr.vscode-js-annotations
code --install-extension ldez.ignore-files
code --install-extension leo-labs.dotnet
code --install-extension letrieu.expand-region
code --install-extension logan-fievez.fast-generate-angular
code --install-extension lucax88x.codeacejumper
code --install-extension luisreinosodev.vscode-ng-file-switcher
code --install-extension lukapetrovic.image-resizer
code --install-extension lukasz-wronski.ftp-sync
code --install-extension lukazakrajsek.scss-refactoring
code --install-extension Lulus.vscode-regexp-preivew
code --install-extension mads-hartmann.bash-ide-vscode
code --install-extension magicstack.MagicPython
code --install-extension Matsuyanagi.split-join-text
code --install-extension mdickin.markdown-shortcuts
code --install-extension Metatype.copilot-vscode
code --install-extension mfery.dotnetexplorer
code --install-extension mhutchie.git-graph
code --install-extension michelemelluso.gitignore
code --install-extension midnightsyntax.vscode-wrap-console-log
code --install-extension mikeburgh.xml-format
code --install-extension mikestead.dotenv
code --install-extension milkmidi.vs-code-quick-require
code --install-extension mindaro-dev.file-downloader
code --install-extension mishkinf.goto-next-previous-member
code --install-extension mkxml.vscode-filesize
code --install-extension mlewand.select-part-of-word
code --install-extension mohsen1.prettify-json
code --install-extension mongodb.mongodb-vscode
code --install-extension mrmlnc.vscode-doiuse
code --install-extension ms-azuretools.vscode-azureappservice
code --install-extension ms-azuretools.vscode-azureresourcegroups
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.blazorwasm-companion
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-mssql.data-workspace-vscode
code --install-extension ms-mssql.mssql
code --install-extension ms-mssql.sql-bindings-vscode
code --install-extension ms-mssql.sql-database-projects-vscode
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.test-adapter-converter
code --install-extension ms-vscode.vscode-github-issue-notebooks
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension mtxr.sqltools
code --install-extension mtxr.sqltools-driver-mssql
code --install-extension mtxr.sqltools-driver-mysql
code --install-extension mujichOk.vscode-project-name-in-statusbar
code --install-extension mycelo.embrace
code --install-extension myxvisual.vscode-ts-uml
code --install-extension NathanMinchow.create-matching-css-file
code --install-extension neptunedesign.vs-html-to-css
code --install-extension nickdemayo.vscode-json-editor
code --install-extension nico-castell.linux-desktop-file
code --install-extension nicoespeon.abracadabra
code --install-extension Nicole.vscode-akita-angular-snippets
code --install-extension nidu.copy-json-path
code --install-extension niklaspor.typescript-jump
code --install-extension nmsmith89.incrementor
code --install-extension NuclleaR.vscode-extension-auto-import
code --install-extension octref.vetur
code --install-extension oleg-shilo.favorites
code --install-extension orenaksakal.vscode-oat
code --install-extension Ottomated.xdg-open-explorer
code --install-extension patcx.vscode-nuget-gallery
code --install-extension Perkovec.emoji
code --install-extension Phu1237.vs-browser
code --install-extension pkyeck.vscode-flatland-icon-theme-custom
code --install-extension plibither8.remove-comments
code --install-extension pmsandhu.webstorm-icons
code --install-extension pomber.git-file-history
code --install-extension pucelle.vscode-css-navigation
code --install-extension qinjia.filenamecomplete
code --install-extension qrti.funclist
code --install-extension qwtel.sqlite-viewer
code --install-extension raathigeshan.fabulous
code --install-extension rahulsahay.Csharp-ASPNETCore
code --install-extension RamiroBerrelleza.bitbucket-pull-requests
code --install-extension Ravi-Rajpurohit.google-search
code --install-extension Rax.vscode-flexbox-picker
code --install-extension rebornix.project-snippets
code --install-extension redhat.java
code --install-extension Remisa.shellman
code --install-extension rioj7.my-code-actions
code --install-extension ritwickdey.create-file-folder
code --install-extension ritwickdey.LiveServer
code --install-extension rogalmic.bash-debug
code --install-extension RohanAgarwal-Vscode.angular-translator
code --install-extension Rubymaniac.vscode-paste-and-indent
code --install-extension ryuta46.multi-command
code --install-extension sachinb94.css-tree
code --install-extension sadeghpm.sql-snippets
code --install-extension sai.autoclass
code --install-extension sallar.json-to-js-object
code --install-extension samuelcolvin.jinjahtml
code --install-extension sandipchitale.vscode-command-window-or-terminal
code --install-extension sensourceinc.vscode-sql-beautify
code --install-extension sgtsquiggs.vscode-active-file-status
code --install-extension shakram02.bash-beautify
code --install-extension Shan.code-settings-sync
code --install-extension shupe.angular-viewer
code --install-extension shuworks.vscode-jump-to-hint
code --install-extension shuworks.vscode-table-formatter
code --install-extension si3792.xray-jump
code --install-extension simonguo.vscode-markdown-table-sort
code --install-extension SimonSiefke.vue-preview
code --install-extension sinchang.packagelinker
code --install-extension sleistner.vscode-fileutils
code --install-extension Smekalin.vue-attr-sort
code --install-extension SonarSource.sonarlint-vscode
code --install-extension spencer-farley.xunitsnippets
code --install-extension srmeyers.git-prefix
code --install-extension Stormspirit.eval
code --install-extension svipas.code-autocomplete
code --install-extension TabNine.tabnine-vscode
code --install-extension tanhakabir.rest-book
code --install-extension tgreen7.vs-code-node-require
code --install-extension theumletteam.umlet
code --install-extension thisismanta.hot-snippet
code --install-extension ThorstenRintelen.angular-spec-generator
code --install-extension tht13.html-preview-vscode
code --install-extension titiaiev.vue-docs
code --install-extension tomoki1207.pdf
code --install-extension tomoyukim.vscode-mermaid-editor
code --install-extension traBpUkciP.wolf
code --install-extension tranhl.find-then-jump
code --install-extension trixnz.go-to-method
code --install-extension ttd-trace-tools.node-chakracore-time-travel-debugger
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension visualzoran.vz-file-templates
code --install-extension vitaliymaz.vscode-svg-previewer
code --install-extension vittorioromeo.expand-selection-to-scope
code --install-extension vmsynkov.colonize
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-snippet.snippet
code --install-extension WakaTime.vscode-wakatime
code --install-extension WallabyJs.quokka-vscode
code --install-extension WASTeamAccount.WebTemplateStudio-dev-nightly
code --install-extension Wilson-Godoi.wg-getters-and-setters
code --install-extension wmaurer.change-case
code --install-extension wware.snippet-creator
code --install-extension wwm.better-align
code --install-extension wyc-iron.apitester
code --install-extension yaegermun.cheater
code --install-extension yannntch.translator-extractor
code --install-extension yatki.vscode-surround
code --install-extension ylw1694.removeEmptyLines
code --install-extension yongwoo.template
code --install-extension yossi-eynav.pull-requester
code --install-extension Yummygum.city-lights-icon-vsc
code --install-extension YuTengjing.open-in-external-app
code --install-extension yutent.scss-to-css
code --install-extension z0gSh1u.vscode-ts-getset
code --install-extension zenghongtu.vscode-asciiflow2
code --install-extension zhoufeng.json-helper
code --install-extension ziishaned.hugobot
code --install-extension zitup.classnametocss
